# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install wheel
  displayName: 'Install dependencies'

- script: |
    rm -r dist
    rm -r build
    rm -r anyoneai.egg-info
  displayName: 'Clear privious build'

- script: |
    ls
    python setup.py install sdist bdist_wheel
  displayName: 'Build'

- script: |
    pip install twine
  displayName: 'Install dependencies for publish'

- task: TwineAuthenticate@0
  inputs:
    externalFeeds: 'PyPi Service Connection'

- script: |
    twine upload -r anyoneai --verbose --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Publish to PyPI'




