# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    cd anyoneai
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    cd ..
  displayName: 'Install dependencies'

- script: |
    rm -r dist
    rm -r build
    rm -r anyoneai.egg-info
  displayName: 'Clear privious build'

- task: PyPIPublisher@0
  inputs:
    pypiConnection: 'Generic PyPi Service Connection'
    packageDirectory: '/'
    alsoPublishWheel: true



- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
